// Generated by gencpp from file pr2_package/PoseSendResponse.msg
// DO NOT EDIT!


#ifndef PR2_PACKAGE_MESSAGE_POSESENDRESPONSE_H
#define PR2_PACKAGE_MESSAGE_POSESENDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pr2_package
{
template <class ContainerAllocator>
struct PoseSendResponse_
{
  typedef PoseSendResponse_<ContainerAllocator> Type;

  PoseSendResponse_()
    : h(0.0)  {
    }
  PoseSendResponse_(const ContainerAllocator& _alloc)
    : h(0.0)  {
  (void)_alloc;
    }



   typedef double _h_type;
  _h_type h;




  typedef boost::shared_ptr< ::pr2_package::PoseSendResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_package::PoseSendResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PoseSendResponse_

typedef ::pr2_package::PoseSendResponse_<std::allocator<void> > PoseSendResponse;

typedef boost::shared_ptr< ::pr2_package::PoseSendResponse > PoseSendResponsePtr;
typedef boost::shared_ptr< ::pr2_package::PoseSendResponse const> PoseSendResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr2_package::PoseSendResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr2_package::PoseSendResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pr2_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'pr2_package': ['/home/tawfiq/pr2_ws/src/pr2_package/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pr2_package::PoseSendResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr2_package::PoseSendResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_package::PoseSendResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_package::PoseSendResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_package::PoseSendResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_package::PoseSendResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr2_package::PoseSendResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59e35b55ce2457dfd5d84cd8269c1541";
  }

  static const char* value(const ::pr2_package::PoseSendResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59e35b55ce2457dfULL;
  static const uint64_t static_value2 = 0xd5d84cd8269c1541ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_package::PoseSendResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr2_package/PoseSendResponse";
  }

  static const char* value(const ::pr2_package::PoseSendResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr2_package::PoseSendResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 h\n\
\n\
";
  }

  static const char* value(const ::pr2_package::PoseSendResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr2_package::PoseSendResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.h);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseSendResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_package::PoseSendResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr2_package::PoseSendResponse_<ContainerAllocator>& v)
  {
    s << indent << "h: ";
    Printer<double>::stream(s, indent + "  ", v.h);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR2_PACKAGE_MESSAGE_POSESENDRESPONSE_H
